pim_icecat_connector:
    settings:
        credentials_username:
            value: ~
            scope: app
        credentials_password:
            value: ~
            scope: app
        locales:
            value: ~
            scope: app
        fallback_locale:
            value: ~
            scope: app
        ean_attribute:
            value: ~
            scope: app
        description:
            value: ~
            scope: app
        short_description:
            value: ~
            scope: app
        summary_description:
            value: ~
            scope: app
        short_summary_description:
            value: ~
            scope: app
        pictures:
            value: ~
            scope: app
